[package]
name = "dfs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
fuser = "0.14.0"
hex = "0.4.3"
libc = "0.2.150"
serde = { version = "1.0.190", features = ["derive", "rc"] }
serde_arrays = "0.1.0"
serde_json = "1.0.108"
sha2 = "0.10.8"
